# Generated by Django 4.1.6 on 2023-04-16 20:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ingrese una breve descripción del producto.",
                        verbose_name="Descripcion del producto",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("image", models.ImageField(upload_to="static/images")),
                ("category", models.CharField(default="", max_length=255)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
