# Generated by Django 4.1.6 on 2023-02-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ingrese una breve descripción del producto.",
                        verbose_name="Descripcion del producto",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("product_image", models.ImageField(upload_to="products/")),
            ],
        ),
    ]
