# Generated by Django 4.1.6 on 2023-02-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_category_product_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/static/images"),
        ),
    ]
