# Generated by Django 3.2.18 on 2023-05-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("cuidado-facial", "Cuidado Facial"),
                    ("maquillaje", "Maquillaje"),
                    ("cuidado-corporal", "Cuidado Corporal"),
                    ("perfumes", "Perfumes"),
                    ("labios", "Labios"),
                    ("cejas", "Cejas"),
                    ("ojos", "Ojos"),
                    ("nails", "Nails"),
                    ("accesorios", "Accesorios"),
                    ("baño-y-ducha", "Baño y Ducha"),
                    ("exfoliantes", "Exfoliantes"),
                    ("hidratantes", "Hidratantes"),
                    ("aceites", "Aceites"),
                    ("protectores-solares", "Protectores Solares"),
                    ("manos", "Manos"),
                    ("pies", "Pies"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="", max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
