# Generated by Django 3.2.18 on 2023-06-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("cuidado-facial", "Cuidado de la Piel"),
                    ("maquillaje", "Maquillaje"),
                    ("cuidado-corporal", "Cuidado Corporal"),
                    ("perfumes", "Perfumes"),
                    ("labios", "Labios"),
                    ("cejas", "Cejas"),
                    ("ojos", "Ojos"),
                    ("nails", "Nails"),
                    ("accesorios", "Accesorios"),
                    ("baño-y-ducha", "Baño y Ducha"),
                    ("exfoliantes", "Exfoliantes"),
                    ("hidratantes", "Hidratantes"),
                    ("aceites", "Aceites"),
                    ("protectores-solares", "Protectores Solares"),
                    ("manos", "Manos"),
                    ("pies", "Pies"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
