# Generated by Django 3.2.18 on 2023-06-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='Ingrese una breve descripción del producto.', verbose_name='Descripcion del producto'),
        ),
    ]
