# Generated by Django 4.1.6 on 2023-03-19 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_payments", "0002_mypayment"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="my_payments.mypayment"
            ),
        ),
    ]
