# Generated by Django 4.1.6 on 2023-04-17 04:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentpayment",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
    ]
