# Generated by Django 4.1.6 on 2023-03-19 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoice_payment"),
        ("my_payments", "0002_mypayment"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.AddField(
            model_name="mypayment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
