# Generated by Django 4.1.6 on 2023-03-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("my_payments", "0003_delete_payment_mypayment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
