# Generated by Django 4.1.6 on 2023-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_payments", "0004_alter_mypayment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypayment",
            name="area_code",
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mypayment",
            name="document_number",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mypayment",
            name="payment_method",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
