# Generated by Django 4.1.6 on 2023-03-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("my_payments", "0005_mypayment_area_code_mypayment_document_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypayment",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
