# Generated by Django 4.1.6 on 2023-03-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0006_appointment_customer"),
        ("my_payments", "0006_alter_mypayment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypayment",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.appointment",
            ),
        ),
    ]
