# Generated by Django 4.1.6 on 2023-03-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_payments", "0007_mypayment_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypayment",
            name="id_mercado_pago",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
