# Generated by Django 4.1.6 on 2023-03-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_payments", "0008_mypayment_id_mercado_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypayment",
            name="id_mercado_pago",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
