# Generated by Django 4.1.6 on 2023-03-06 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_appointment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="profesional",
            new_name="professional",
        ),
    ]
