# Generated by Django 4.1.6 on 2023-03-19 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_rename_profesional_appointment_professional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="shopping_cart",
        ),
    ]
