# Generated by Django 4.1.6 on 2023-03-21 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0005_remove_appointment_appointment_slot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
