# Generated by Django 4.1.6 on 2023-02-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TH", "Threading"),
                            ("MN", "Manos"),
                            ("PD", "Pies"),
                            ("FC", "Cuidado de la piel"),
                            ("BW", "Cejas"),
                            ("EL", "Pestañas"),
                            ("LP", "Labios"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ingrese una breve descripción del servicio.",
                        verbose_name="Product Description",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (30, "30 min"),
                            (60, "60 min"),
                            (90, "90 min"),
                            (120, "120 min"),
                            (150, "150 min"),
                            (180, "180 min"),
                        ]
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.categoryservice",
                    ),
                ),
            ],
        ),
    ]
