# Generated by Django 3.2.18 on 2023-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryservice",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
