# Generated by Django 3.2.18 on 2023-05-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_categoryservice_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Ingrese una breve descripción del servicio.",
                verbose_name="Descripción del producto",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
