# Generated by Django 3.2.18 on 2023-05-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_auto_20230522_0047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
